server:
  initial_number_of_daemons: 3
aws:
  credentials:
    access_key_id: "access_key_id"
    secret_access_key: "secret_access_key"
processors:
  sample:
    queue: 'sample' # can be omitted
    publisher:
      delay: 5
    workers:
      initial: 3