aws:
  credentials:
    access_key_id: "access_key_id"
    secret_access_key: "secret_access_key"
processors:
  sample:
    queue: 'sample' # can be omitted
    publishers:
      delay: 30
    workers:
      initial: 3
      data_store:
        class: s3
  error:
    publishers:
      delay: 30
    workers:
      initial: 1